/**
 * Handover service (H9 — "proper" Claude Code handover).
 *
 * Replaces the old "one markdown file + external terminal" flow with a real,
 * reusable HANDOVER BUNDLE plus an optional in-app agentic run. See
 * docs/specs/2026-07-11-pluggable-brains-and-handover.md §E.
 *
 *   handover/<timestamped-slug>/
 *     HANDOVER.md          # the generated handoff prompt (claude_code_prompt core)
 *     README.md            # "generated by HiDock Next — start with HANDOVER.md"
 *     manifest.json        # { generatedAt, brain, source ids, files }
 *     context/
 *       transcript.md      # full transcript
 *       summary.md         # analysis summary
 *       action-items.md    # extracted action items + detected actionables
 *       decisions.md       # key points / decisions
 *       meeting.json       # { subject, date, attendees, meetingId, recordingIds }
 *     RUN.log              # (created only when the agent is run) run progress/result
 *
 * The bundle assembler is pure filesystem + DB reads (fully unit-testable via
 * injected data + a real temp dir). The agentic run resolves an AGENTIC brain via
 * the BrainRouter (task 'handover', capability 'agentic') and uses the brain's
 * `generate()` as the invocation surface — honouring the never-throw / null
 * contract (a null result is a SURFACED failure, not silence). No adapter internals
 * are touched here; this service only consumes the public brains seam.
 */
import { mkdirSync, writeFileSync, appendFileSync, realpathSync, lstatSync } from 'fs'
import { join, parse, resolve, sep } from 'path'
import { randomBytes, randomUUID } from 'crypto'
import {
  getTranscriptByRecordingId,
  getMeetingById,
  getRecordingById,
  queryOne,
  queryAll,
} from './database'
import { getBrainRouter, getBrainRegistry } from './brains'
import type { AIBrain } from './brains'
import { getEventBus } from './event-bus'

/** Source the handover was generated from (any subset resolves the rest via DB). */
export interface HandoverSourceRef {
  actionableId?: string
  knowledgeCaptureId?: string
  meetingId?: string
  recordingId?: string
}

/** Small, serialisable record of what the bundle contains + where it came from. */
export interface HandoverManifest {
  slug: string
  title: string
  generatedAt: string
  brain: { id: string; label: string } | null
  source: {
    actionableId: string | null
    knowledgeCaptureId: string | null
    meetingId: string | null
    recordingIds: string[]
  }
  /** Bundle-relative paths of every file written (POSIX separators). */
  files: string[]
}

export interface AssembleBundleParams {
  /** Directory the bundle folder is created under (the target repo/dir). */
  targetDir: string
  /** The HANDOVER.md core — reuse of the claude_code_prompt template output. */
  handoverContent: string
  source: HandoverSourceRef
  /** The brain that will run (or ran) the handover, recorded in the manifest. */
  brain?: { id: string; label: string } | null
  /**
   * Additional canonical paths (app install dir, userData, …) the caller wants
   * refused as targets, on top of the built-in OS-protected list. The IPC handler
   * passes the Electron app paths here (this module stays Electron-free).
   */
  extraProtectedPaths?: string[]
  /** Injected for tests. Defaults to a live clock. */
  now?: () => Date
  /** Injected for tests. Defaults to DB-backed readers. */
  data?: Partial<HandoverDataDeps>
}

export interface AssembleBundleResult {
  /**
   * Opaque id for this bundle in the main-process registry. The ONLY token the
   * renderer may pass back to run the agent — paths from the renderer are never
   * trusted for execution.
   */
  bundleId: string
  bundleDir: string
  handoverPath: string
  /** The canonicalized (realpath) target directory the bundle was written under. */
  targetDir: string
  manifest: HandoverManifest
}

/**
 * DB reader seam. Defaults bind to database.ts; tests pass fakes so the assembler
 * can be exercised against a real temp directory with no database.
 */
export interface HandoverDataDeps {
  getActionable: (id: string) => { source_knowledge_id: string | null } | undefined
  getKnowledgeCapture: (
    id: string
  ) =>
    | { id: string; title?: string; summary?: string; source_recording_id?: string | null; meeting_id?: string | null; captured_at?: string }
    | undefined
  getRecording: (id: string) => { id: string; filename?: string; meeting_id?: string | null; date_recorded?: string } | undefined
  getTranscript: (
    recordingId: string
  ) => { full_text?: string; summary?: string; action_items?: string; key_points?: string; topics?: string } | undefined
  getMeeting: (id: string) => { id: string; subject?: string; start_time?: string; attendees?: string } | undefined
  getActionablesForKnowledge: (knowledgeId: string) => Array<{ title: string; description?: string; type?: string; status?: string }>
}

const defaultDataDeps: HandoverDataDeps = {
  getActionable: (id) => queryOne<{ source_knowledge_id: string | null }>('SELECT source_knowledge_id FROM actionables WHERE id = ?', [id]),
  getKnowledgeCapture: (id) =>
    queryOne('SELECT id, title, summary, source_recording_id, meeting_id, captured_at FROM knowledge_captures WHERE id = ?', [id]),
  getRecording: (id) => getRecordingById(id) as any,
  getTranscript: (recordingId) => getTranscriptByRecordingId(recordingId) as any,
  getMeeting: (id) => getMeetingById(id) as any,
  getActionablesForKnowledge: (knowledgeId) =>
    queryAll<{ title: string; description?: string; type?: string; status?: string }>(
      'SELECT title, description, type, status FROM actionables WHERE source_knowledge_id = ? ORDER BY created_at',
      [knowledgeId]
    ),
}

interface ResolvedSource {
  actionableId: string | null
  knowledgeCaptureId: string | null
  meetingId: string | null
  recordingIds: string[]
  title: string
  transcriptText: string
  summaryText: string
  actionItemsText: string
  decisionsText: string
  meetingJson: {
    subject: string | null
    date: string | null
    attendees: string[]
    meetingId: string | null
    recordingIds: string[]
    knowledgeCaptureId: string | null
  }
}

/** Lowercase, hyphenated, bounded slug from a free-text title. */
export function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'handover'
  )
}

/** Timestamped directory prefix: YYYY-MM-DD-HHmmss (local time). */
function timestampSlug(now: Date): string {
  const p = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${p(now.getMonth() + 1)}-${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}${p(now.getSeconds())}`
}

// ── Target validation, bundle registry, atomic reservation (security) ─────────

/** Normalize a path for comparison: canonical form, lowercased on Windows. */
function comparable(p: string): string {
  const r = resolve(p)
  return process.platform === 'win32' ? r.toLowerCase() : r
}

/** OS-protected roots the handover must never write into (built-in list). */
function builtinProtectedPaths(env: NodeJS.ProcessEnv = process.env): string[] {
  const list: string[] = []
  for (const v of [env.SystemRoot, env.windir, env.ProgramFiles, env['ProgramFiles(x86)'], env.ProgramData]) {
    if (v && v.trim()) list.push(v)
  }
  if (process.platform !== 'win32') list.push('/etc', '/usr', '/bin', '/sbin', '/boot', '/System', '/Library')
  return list
}

/**
 * Canonicalize and vet a renderer-supplied target directory. Throws with a
 * user-facing message when the target is unusable:
 *   - does not exist / not a directory (realpath resolves symlinks — the
 *     CANONICAL location is what gets vetted and used from here on);
 *   - is a filesystem root (C:\, /);
 *   - is (or is inside) a protected OS location or a caller-supplied protected
 *     path (app install dir, userData — passed by the IPC handler).
 * Returns the canonical real path.
 */
export function validateTargetDir(
  targetDir: string,
  extraProtectedPaths: string[] = [],
  env: NodeJS.ProcessEnv = process.env
): string {
  let canonical: string
  try {
    canonical = realpathSync(targetDir)
  } catch {
    throw new Error(`The handover folder does not exist: ${targetDir}`)
  }
  if (!lstatSync(canonical).isDirectory()) {
    throw new Error(`The handover target is not a directory: ${targetDir}`)
  }

  const c = comparable(canonical)
  const root = parse(canonical).root
  if (c === comparable(root)) {
    throw new Error('The handover target cannot be a filesystem root. Pick a project folder.')
  }

  for (const protectedPath of [...builtinProtectedPaths(env), ...extraProtectedPaths]) {
    const p = comparable(protectedPath)
    if (c === p || c.startsWith(p + sep)) {
      throw new Error(`The handover target is inside a protected location (${protectedPath}). Pick a project folder.`)
    }
  }
  return canonical
}

/**
 * Main-process bundle registry. `handover:runAgent` accepts ONLY an opaque
 * bundleId minted here — a renderer can never point the runner at an arbitrary
 * path. In-memory by design: a bundle is runnable in the session that created it.
 */
export interface BundleRecord {
  bundleDir: string
  targetDir: string
  createdAt: string
}

const bundleRegistry = new Map<string, BundleRecord>()
/** BundleIds with an agent run currently in flight (concurrency guard). */
const activeRuns = new Set<string>()

export function getRegisteredBundle(bundleId: string): BundleRecord | undefined {
  return bundleRegistry.get(bundleId)
}

/** Test helper: clear the registry + active-run tracking. */
export function resetHandoverRegistry(): void {
  bundleRegistry.clear()
  activeRuns.clear()
}

/**
 * Atomically reserve a fresh bundle directory: `mkdirSync(..., recursive: false)`
 * either creates it or throws EEXIST — no check-then-use window. On collision
 * (same slug in the same second, or a concurrent create) retry with a random
 * suffix. Never reuses or overwrites an existing directory.
 */
function reserveBundleDir(parentDir: string, slug: string): string {
  const candidates = [join(parentDir, slug)]
  for (let i = 0; i < 8; i++) {
    candidates.push(join(parentDir, `${slug}-${randomBytes(3).toString('hex')}`))
  }
  for (const candidate of candidates) {
    try {
      mkdirSync(candidate, { recursive: false })
      return candidate
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === 'EEXIST') continue
      throw e
    }
  }
  throw new Error('Could not reserve a handover bundle directory (too many collisions).')
}

/** Parse the transcript's stored action_items (JSON array or plain text) to markdown. */
function formatActionItems(raw: string | undefined, detected: Array<{ title: string; description?: string; type?: string; status?: string }>): string {
  const lines: string[] = ['# Action Items', '']
  const fromTranscript: string[] = []
  if (raw && raw.trim()) {
    try {
      const parsed = JSON.parse(raw)
      if (Array.isArray(parsed)) {
        for (const item of parsed) {
          if (typeof item === 'string') fromTranscript.push(item)
          else if (item && typeof item === 'object') {
            const owner = (item.owner || item.assignee || '').toString().trim()
            const task = (item.task || item.action || item.title || item.text || '').toString().trim()
            const due = (item.due || item.dueDate || '').toString().trim()
            const parts = [task, owner ? `— ${owner}` : '', due ? `(due ${due})` : ''].filter(Boolean)
            if (parts.length) fromTranscript.push(parts.join(' '))
          }
        }
      } else {
        fromTranscript.push(raw.trim())
      }
    } catch {
      fromTranscript.push(raw.trim())
    }
  }

  if (fromTranscript.length) {
    lines.push('## From the transcript', '')
    for (const t of fromTranscript) lines.push(`- ${t}`)
    lines.push('')
  }

  if (detected.length) {
    lines.push('## Detected actionables', '')
    for (const a of detected) {
      const suffix = a.status ? ` _(status: ${a.status})_` : ''
      lines.push(`- **${a.title}**${suffix}`)
      if (a.description && a.description.trim()) lines.push(`  ${a.description.trim()}`)
    }
    lines.push('')
  }

  if (!fromTranscript.length && !detected.length) {
    lines.push('None recorded.', '')
  }
  return lines.join('\n')
}

/** Resolve the full source (mirrors output-generator + resolveProjectFolderForActionable). */
function resolveSource(ref: HandoverSourceRef, deps: HandoverDataDeps): ResolvedSource {
  const actionableId = ref.actionableId ?? null
  let knowledgeCaptureId = ref.knowledgeCaptureId ?? null

  // An actionable's source_knowledge_id is either a capture id OR a recording id.
  let skid: string | null = knowledgeCaptureId
  if (actionableId) {
    const a = deps.getActionable(actionableId)
    if (a?.source_knowledge_id) skid = a.source_knowledge_id
  }

  const kc = skid ? deps.getKnowledgeCapture(skid) : undefined
  let recordingId = ref.recordingId ?? null
  let meetingId = ref.meetingId ?? null

  if (kc) {
    knowledgeCaptureId = kc.id
    recordingId = recordingId ?? kc.source_recording_id ?? null
    meetingId = meetingId ?? kc.meeting_id ?? null
  } else if (skid) {
    // No capture row → treat skid as a recording id.
    recordingId = recordingId ?? skid
  }

  const rec = recordingId ? deps.getRecording(recordingId) : undefined
  if (rec) meetingId = meetingId ?? rec.meeting_id ?? null

  const transcript = recordingId ? deps.getTranscript(recordingId) : undefined
  const meeting = meetingId ? deps.getMeeting(meetingId) : undefined
  const knowledgeKey = knowledgeCaptureId ?? skid
  const detected = knowledgeKey ? deps.getActionablesForKnowledge(knowledgeKey) : []

  const title = (kc?.title || meeting?.subject || rec?.filename || 'handover').toString()
  const attendees = (meeting?.attendees || '')
    .split(/[;,\n]/)
    .map((s) => s.trim())
    .filter(Boolean)
  const recordingIds = recordingId ? [recordingId] : []

  const summaryText = (transcript?.summary || kc?.summary || 'No summary available.').trim() || 'No summary available.'
  const decisionsRaw = (transcript?.key_points || '').trim()
  const decisionsText = decisionsRaw
    ? `# Key Points / Decisions\n\n${decisionsRaw}`
    : '# Key Points / Decisions\n\nNone recorded.'

  return {
    actionableId,
    knowledgeCaptureId,
    meetingId,
    recordingIds,
    title,
    transcriptText: (transcript?.full_text || 'No transcript available.').trim() || 'No transcript available.',
    summaryText: `# Summary\n\n${summaryText}`,
    actionItemsText: formatActionItems(transcript?.action_items, detected),
    decisionsText,
    meetingJson: {
      subject: meeting?.subject ?? null,
      date: meeting?.start_time ?? rec?.date_recorded ?? null,
      attendees,
      meetingId,
      recordingIds,
      knowledgeCaptureId,
    },
  }
}

const README_BODY = `# HiDock Next — Handover Bundle

This folder was generated by **HiDock Next** to hand a meeting's follow-up work
to an AI coding agent (Claude Code / Codex / Gemini CLI).

**Start with \`HANDOVER.md\`** — it is a self-contained prompt describing the work
to do. The \`context/\` folder holds the supporting material the prompt refers to:

- \`context/transcript.md\` — the full meeting transcript
- \`context/summary.md\` — the analysis summary
- \`context/action-items.md\` — extracted action items and detected actionables
- \`context/decisions.md\` — key points / decisions
- \`context/meeting.json\` — meeting metadata (subject, date, attendees, ids)

\`manifest.json\` records which recording/meeting this came from, when it was
generated, and which AI brain was selected. If the agent was run in-app, its
progress and result are appended to \`RUN.log\`.
`

/**
 * Assemble the handover bundle on disk. Pure filesystem + DB reads — no LLM calls,
 * no network. The target directory is canonicalized and vetted (protected paths
 * rejected), the `handover` parent must not be a symlink/junction, the bundle dir
 * is reserved ATOMICALLY, and its real path is verified to be contained under the
 * canonical target — then the bundle is registered under an opaque bundleId which
 * is the only token `runAgent` accepts.
 */
export function assembleHandoverBundle(params: AssembleBundleParams): AssembleBundleResult {
  const now = (params.now ?? (() => new Date()))()
  const deps: HandoverDataDeps = { ...defaultDataDeps, ...(params.data ?? {}) }

  // 1. Canonicalize + vet the target (throws a user-facing error when refused).
  const canonicalTarget = validateTargetDir(params.targetDir, params.extraProtectedPaths ?? [])

  // 2. The `handover` parent must be a REAL directory directly under the target —
  //    a symlink/junction here would let bundle writes escape the vetted target.
  const parentDir = join(canonicalTarget, 'handover')
  try {
    const st = lstatSync(parentDir)
    if (st.isSymbolicLink() || !st.isDirectory()) {
      throw new Error('The "handover" folder inside the target is a link or not a directory. Remove it and retry.')
    }
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === 'ENOENT') {
      mkdirSync(parentDir) // non-recursive: canonicalTarget is known to exist
    } else {
      throw e
    }
  }

  const resolved = resolveSource(params.source, deps)
  // Slug = timestamp + slugify output: strictly [a-z0-9-], so no separators,
  // no dot segments, and (with the timestamp prefix) no Windows reserved names —
  // the transcript-derived title is untrusted input.
  const slug = `${timestampSlug(now)}-${slugify(resolved.title)}`

  // 3. Reserve the bundle directory atomically (no check-then-use window).
  const bundleDir = reserveBundleDir(parentDir, slug)

  // 4. Containment post-check: the REAL bundle path must live under the canonical
  //    target (belt-and-suspenders against reparse-point tricks between checks).
  const realBundle = comparable(realpathSync(bundleDir))
  if (realBundle !== comparable(bundleDir) || !realBundle.startsWith(comparable(canonicalTarget) + sep)) {
    throw new Error('Handover bundle path escaped the target directory — aborting.')
  }

  const contextDir = join(bundleDir, 'context')
  mkdirSync(contextDir)

  const files: Array<{ rel: string; content: string }> = [
    { rel: 'HANDOVER.md', content: params.handoverContent },
    { rel: 'README.md', content: README_BODY },
    { rel: 'context/transcript.md', content: `# Transcript\n\n${resolved.transcriptText}\n` },
    { rel: 'context/summary.md', content: `${resolved.summaryText}\n` },
    { rel: 'context/action-items.md', content: `${resolved.actionItemsText}\n` },
    { rel: 'context/decisions.md', content: `${resolved.decisionsText}\n` },
    { rel: 'context/meeting.json', content: JSON.stringify(resolved.meetingJson, null, 2) },
  ]

  const manifest: HandoverManifest = {
    slug,
    title: resolved.title,
    generatedAt: now.toISOString(),
    brain: params.brain ?? null,
    source: {
      actionableId: resolved.actionableId,
      knowledgeCaptureId: resolved.knowledgeCaptureId,
      meetingId: resolved.meetingId,
      recordingIds: resolved.recordingIds,
    },
    files: files.map((f) => f.rel).concat('manifest.json'),
  }

  for (const f of files) writeFileSync(join(bundleDir, f.rel), f.content, 'utf-8')
  writeFileSync(join(bundleDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8')

  // 5. Register under an opaque id — the only token runAgent accepts back.
  const bundleId = randomUUID()
  bundleRegistry.set(bundleId, { bundleDir, targetDir: canonicalTarget, createdAt: now.toISOString() })

  return { bundleId, bundleDir, handoverPath: join(bundleDir, 'HANDOVER.md'), targetDir: canonicalTarget, manifest }
}

// ── Agentic run ────────────────────────────────────────────────────────────────

export interface RunHandoverAgentParams {
  /**
   * Opaque bundle id minted by assembleHandoverBundle. The bundle/target paths
   * are looked up in the main-process registry — renderer-supplied paths are
   * NEVER accepted for execution.
   */
  bundleId: string
  /** Explicit brain to use; when absent the router resolves the 'handover' task. */
  brainId?: string
  signal?: AbortSignal
  /** Injected for tests. */
  now?: () => Date
  /** Injected for tests. */
  resolveBrain?: (brainId?: string) => Promise<AIBrain | null>
  /** Injected for tests. */
  emit?: (type: string, payload: Record<string, unknown>) => void
  /** Injected for tests. Defaults to the main-process bundle registry. */
  lookupBundle?: (bundleId: string) => BundleRecord | undefined
}

export interface RunHandoverAgentResult {
  ok: boolean
  brainId: string | null
  brainLabel: string | null
  finalResponse: string | null
  runLogPath: string
  error?: string
}

/**
 * Resolve the agentic brain for a run: an explicit, enabled, configured, agentic
 * brain wins; otherwise the BrainRouter resolves the 'handover' task with the
 * 'agentic' capability (respecting Settings default/routing). Returns null when no
 * agentic brain is usable — the caller surfaces that as a failure, never silence.
 */
async function defaultResolveBrain(brainId?: string): Promise<AIBrain | null> {
  if (brainId) {
    const brain = getBrainRegistry().get(brainId as AIBrain['id'])
    if (brain && brain.capabilities().has('agentic')) {
      try {
        if ((await brain.authStatus()).configured) return brain
      } catch {
        /* fall through to the router */
      }
    }
  }
  return getBrainRouter().resolve('handover', 'agentic')
}

function buildRunPrompt(bundleDir: string, targetDir: string): string {
  const handoverPath = join(bundleDir, 'HANDOVER.md')
  const contextDir = join(bundleDir, 'context')
  return [
    'You are receiving a handover of follow-up work from HiDock Next.',
    '',
    `A handover bundle has been written to:`,
    `  ${bundleDir}`,
    '',
    `1. First read the handover prompt: "${handoverPath}".`,
    `2. Then read the supporting material in "${contextDir}" (transcript, summary, action items, decisions, meeting metadata).`,
    '',
    `Your working directory for this task is:`,
    `  ${targetDir}`,
    '',
    'Carry out the follow-up work described in the handover prompt, operating inside that working directory.',
  ].join('\n')
}

/**
 * Run the handover through an agentic brain, in-app. The bundle/target paths come
 * ONLY from the main-process registry (opaque bundleId); one run per bundle at a
 * time. Writes a RUN.log alongside the bundle and emits event-bus events so the
 * Activity Log can surface progress. Uses the brain's `generate()` as the
 * invocation surface — the validated target directory is passed as the child
 * process cwd (GenerateOptions.cwd) — and honours the never-throw / null
 * contract: a null result is a surfaced failure written to RUN.log, not silence.
 */
export async function runHandoverAgent(params: RunHandoverAgentParams): Promise<RunHandoverAgentResult> {
  const now = params.now ?? (() => new Date())
  const resolveBrain = params.resolveBrain ?? defaultResolveBrain
  const lookupBundle = params.lookupBundle ?? getRegisteredBundle
  const emit =
    params.emit ??
    ((type: string, payload: Record<string, unknown>) =>
      getEventBus().emitDomainEvent({ type, timestamp: now().toISOString(), payload }))

  // Only bundles minted by this process are runnable — a forged/unknown id (or a
  // path smuggled in as an id) resolves to nothing and is refused.
  const record = lookupBundle(params.bundleId)
  if (!record) {
    const error = 'Unknown handover bundle. Write the bundle again and retry.'
    emit('handover:run-failed', { bundleId: params.bundleId, brainId: params.brainId ?? null, error })
    return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath: '', error }
  }
  const { bundleDir, targetDir } = record
  const runLogPath = join(bundleDir, 'RUN.log')

  // One run per bundle: a second concurrent run would interleave RUN.log lines
  // indistinguishably and double-execute the same work.
  if (activeRuns.has(params.bundleId)) {
    const error = 'This handover bundle already has an agent run in progress.'
    emit('handover:run-failed', { bundleId: params.bundleId, brainId: params.brainId ?? null, error })
    return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath, error }
  }
  activeRuns.add(params.bundleId)

  const appendLog = (line: string) => {
    try {
      appendFileSync(runLogPath, line.endsWith('\n') ? line : `${line}\n`, 'utf-8')
    } catch (e) {
      console.error('[handover] failed to append RUN.log:', e)
    }
  }

  try {
    const brain = await resolveBrain(params.brainId)
    if (!brain) {
      const error =
        'No agentic AI brain is available. Enable and sign in to Claude Code, Codex, or Gemini CLI in Settings → AI Brains.'
      appendLog(`[${now().toISOString()}] HANDOVER RUN FAILED — ${error}`)
      emit('handover:run-failed', { bundleDir, brainId: params.brainId ?? null, error })
      return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath, error }
    }

    // Fail closed on cwd: only brains advertising 'agentic' honour
    // GenerateOptions.cwd (they spawn a CLI via runCli). Refuse anything else
    // rather than silently running in Electron's cwd.
    if (!brain.capabilities().has('agentic')) {
      const error = `The selected brain (${brain.label}) cannot run in a working directory. Pick an agentic brain.`
      appendLog(`[${now().toISOString()}] HANDOVER RUN FAILED — ${error}`)
      emit('handover:run-failed', { bundleDir, brainId: brain.id, error })
      return { ok: false, brainId: brain.id, brainLabel: brain.label, finalResponse: null, runLogPath, error }
    }

    const started = now().toISOString()
    appendLog(`[${started}] HANDOVER RUN STARTED`)
    appendLog(`  brain: ${brain.label} (${brain.id})`)
    appendLog(`  target: ${targetDir}`)
    appendLog(`  bundle: ${bundleDir}`)
    appendLog('')
    emit('handover:run-started', { bundleDir, brainId: brain.id, targetDir })

    const prompt = buildRunPrompt(bundleDir, targetDir)

    let finalResponse: string | null = null
    try {
      // `generate()` NEVER throws by contract — it returns null on failure/cancel.
      // cwd = the validated target: the CLI child process actually runs there.
      finalResponse = await brain.generate([{ role: 'user', content: prompt }], {
        signal: params.signal,
        cwd: targetDir,
      })
    } catch (e) {
      // Defensive: even though the contract forbids it, never let a throw escape.
      console.error('[handover] brain.generate threw (contract violation):', e)
      finalResponse = null
    }

    const ended = now().toISOString()
    if (finalResponse && finalResponse.trim()) {
      appendLog(finalResponse.trim())
      appendLog('')
      appendLog(`[${ended}] HANDOVER RUN COMPLETED`)
      emit('handover:run-completed', { bundleDir, brainId: brain.id, ok: true })
      return { ok: true, brainId: brain.id, brainLabel: brain.label, finalResponse: finalResponse.trim(), runLogPath }
    }

    const error =
      'The agent returned no output — it may have failed, been cancelled, timed out, or not be authenticated. Check Settings → AI Brains.'
    appendLog(`[${ended}] HANDOVER RUN FAILED — ${error}`)
    emit('handover:run-failed', { bundleDir, brainId: brain.id, error })
    return { ok: false, brainId: brain.id, brainLabel: brain.label, finalResponse: null, runLogPath, error }
  } finally {
    activeRuns.delete(params.bundleId)
  }
}
