/**
 * Handover service (H9 — "proper" Claude Code handover).
 *
 * Replaces the old "one markdown file + external terminal" flow with a real,
 * reusable HANDOVER BUNDLE plus an optional in-app agentic run. See
 * docs/specs/2026-07-11-pluggable-brains-and-handover.md §E.
 *
 *   handover/<timestamped-slug>/
 *     HANDOVER.md          # the generated handoff prompt (claude_code_prompt core)
 *     README.md            # "generated by HiDock Next — start with HANDOVER.md"
 *     manifest.json        # { generatedAt, brain, source ids, files }
 *     context/
 *       transcript.md      # full transcript
 *       summary.md         # analysis summary
 *       action-items.md    # extracted action items + detected actionables
 *       decisions.md       # key points / decisions
 *       meeting.json       # { subject, date, attendees, meetingId, recordingIds }
 *     RUN.log              # (created only when the agent is run) run progress/result
 *
 * The bundle assembler is pure filesystem + DB reads (fully unit-testable via
 * injected data + a real temp dir). The agentic run resolves an AGENTIC brain via
 * the BrainRouter (task 'handover', capability 'agentic') and uses the brain's
 * `generate()` as the invocation surface — honouring the never-throw / null
 * contract (a null result is a SURFACED failure, not silence). No adapter internals
 * are touched here; this service only consumes the public brains seam.
 */
import { mkdirSync, writeFileSync, existsSync, appendFileSync } from 'fs'
import { join } from 'path'
import {
  getTranscriptByRecordingId,
  getMeetingById,
  getRecordingById,
  queryOne,
  queryAll,
} from './database'
import { getBrainRouter, getBrainRegistry } from './brains'
import type { AIBrain } from './brains'
import { getEventBus } from './event-bus'

/** Source the handover was generated from (any subset resolves the rest via DB). */
export interface HandoverSourceRef {
  actionableId?: string
  knowledgeCaptureId?: string
  meetingId?: string
  recordingId?: string
}

/** Small, serialisable record of what the bundle contains + where it came from. */
export interface HandoverManifest {
  slug: string
  title: string
  generatedAt: string
  brain: { id: string; label: string } | null
  source: {
    actionableId: string | null
    knowledgeCaptureId: string | null
    meetingId: string | null
    recordingIds: string[]
  }
  /** Bundle-relative paths of every file written (POSIX separators). */
  files: string[]
}

export interface AssembleBundleParams {
  /** Directory the bundle folder is created under (the target repo/dir). */
  targetDir: string
  /** The HANDOVER.md core — reuse of the claude_code_prompt template output. */
  handoverContent: string
  source: HandoverSourceRef
  /** The brain that will run (or ran) the handover, recorded in the manifest. */
  brain?: { id: string; label: string } | null
  /** Injected for tests. Defaults to a live clock. */
  now?: () => Date
  /** Injected for tests. Defaults to DB-backed readers. */
  data?: Partial<HandoverDataDeps>
  /** Injected for tests. Defaults to fs.existsSync. */
  pathExists?: (p: string) => boolean
}

export interface AssembleBundleResult {
  bundleDir: string
  handoverPath: string
  manifest: HandoverManifest
}

/**
 * DB reader seam. Defaults bind to database.ts; tests pass fakes so the assembler
 * can be exercised against a real temp directory with no database.
 */
export interface HandoverDataDeps {
  getActionable: (id: string) => { source_knowledge_id: string | null } | undefined
  getKnowledgeCapture: (
    id: string
  ) =>
    | { id: string; title?: string; summary?: string; source_recording_id?: string | null; meeting_id?: string | null; captured_at?: string }
    | undefined
  getRecording: (id: string) => { id: string; filename?: string; meeting_id?: string | null; date_recorded?: string } | undefined
  getTranscript: (
    recordingId: string
  ) => { full_text?: string; summary?: string; action_items?: string; key_points?: string; topics?: string } | undefined
  getMeeting: (id: string) => { id: string; subject?: string; start_time?: string; attendees?: string } | undefined
  getActionablesForKnowledge: (knowledgeId: string) => Array<{ title: string; description?: string; type?: string; status?: string }>
}

const defaultDataDeps: HandoverDataDeps = {
  getActionable: (id) => queryOne<{ source_knowledge_id: string | null }>('SELECT source_knowledge_id FROM actionables WHERE id = ?', [id]),
  getKnowledgeCapture: (id) =>
    queryOne('SELECT id, title, summary, source_recording_id, meeting_id, captured_at FROM knowledge_captures WHERE id = ?', [id]),
  getRecording: (id) => getRecordingById(id) as any,
  getTranscript: (recordingId) => getTranscriptByRecordingId(recordingId) as any,
  getMeeting: (id) => getMeetingById(id) as any,
  getActionablesForKnowledge: (knowledgeId) =>
    queryAll<{ title: string; description?: string; type?: string; status?: string }>(
      'SELECT title, description, type, status FROM actionables WHERE source_knowledge_id = ? ORDER BY created_at',
      [knowledgeId]
    ),
}

interface ResolvedSource {
  actionableId: string | null
  knowledgeCaptureId: string | null
  meetingId: string | null
  recordingIds: string[]
  title: string
  transcriptText: string
  summaryText: string
  actionItemsText: string
  decisionsText: string
  meetingJson: {
    subject: string | null
    date: string | null
    attendees: string[]
    meetingId: string | null
    recordingIds: string[]
    knowledgeCaptureId: string | null
  }
}

/** Lowercase, hyphenated, bounded slug from a free-text title. */
export function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'handover'
  )
}

/** Timestamped directory prefix: YYYY-MM-DD-HHmmss (local time). */
function timestampSlug(now: Date): string {
  const p = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${p(now.getMonth() + 1)}-${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}${p(now.getSeconds())}`
}

/**
 * Pick a bundle directory that does not already exist. On collision (same slug in
 * the same second) append `-2`, `-3`, … — never overwrite an existing bundle.
 * `pathExists` is injected for hermetic tests.
 */
export function resolveUniqueBundleDir(
  parentDir: string,
  slug: string,
  pathExists: (p: string) => boolean = existsSync
): string {
  const base = join(parentDir, slug)
  if (!pathExists(base)) return base
  for (let i = 2; i < 1000; i++) {
    const candidate = join(parentDir, `${slug}-${i}`)
    if (!pathExists(candidate)) return candidate
  }
  // Extremely unlikely; fall back to a random-ish suffix.
  return join(parentDir, `${slug}-${Date.now()}`)
}

/** Parse the transcript's stored action_items (JSON array or plain text) to markdown. */
function formatActionItems(raw: string | undefined, detected: Array<{ title: string; description?: string; type?: string; status?: string }>): string {
  const lines: string[] = ['# Action Items', '']
  const fromTranscript: string[] = []
  if (raw && raw.trim()) {
    try {
      const parsed = JSON.parse(raw)
      if (Array.isArray(parsed)) {
        for (const item of parsed) {
          if (typeof item === 'string') fromTranscript.push(item)
          else if (item && typeof item === 'object') {
            const owner = (item.owner || item.assignee || '').toString().trim()
            const task = (item.task || item.action || item.title || item.text || '').toString().trim()
            const due = (item.due || item.dueDate || '').toString().trim()
            const parts = [task, owner ? `— ${owner}` : '', due ? `(due ${due})` : ''].filter(Boolean)
            if (parts.length) fromTranscript.push(parts.join(' '))
          }
        }
      } else {
        fromTranscript.push(raw.trim())
      }
    } catch {
      fromTranscript.push(raw.trim())
    }
  }

  if (fromTranscript.length) {
    lines.push('## From the transcript', '')
    for (const t of fromTranscript) lines.push(`- ${t}`)
    lines.push('')
  }

  if (detected.length) {
    lines.push('## Detected actionables', '')
    for (const a of detected) {
      const suffix = a.status ? ` _(status: ${a.status})_` : ''
      lines.push(`- **${a.title}**${suffix}`)
      if (a.description && a.description.trim()) lines.push(`  ${a.description.trim()}`)
    }
    lines.push('')
  }

  if (!fromTranscript.length && !detected.length) {
    lines.push('None recorded.', '')
  }
  return lines.join('\n')
}

/** Resolve the full source (mirrors output-generator + resolveProjectFolderForActionable). */
function resolveSource(ref: HandoverSourceRef, deps: HandoverDataDeps): ResolvedSource {
  const actionableId = ref.actionableId ?? null
  let knowledgeCaptureId = ref.knowledgeCaptureId ?? null

  // An actionable's source_knowledge_id is either a capture id OR a recording id.
  let skid: string | null = knowledgeCaptureId
  if (actionableId) {
    const a = deps.getActionable(actionableId)
    if (a?.source_knowledge_id) skid = a.source_knowledge_id
  }

  const kc = skid ? deps.getKnowledgeCapture(skid) : undefined
  let recordingId = ref.recordingId ?? null
  let meetingId = ref.meetingId ?? null

  if (kc) {
    knowledgeCaptureId = kc.id
    recordingId = recordingId ?? kc.source_recording_id ?? null
    meetingId = meetingId ?? kc.meeting_id ?? null
  } else if (skid) {
    // No capture row → treat skid as a recording id.
    recordingId = recordingId ?? skid
  }

  const rec = recordingId ? deps.getRecording(recordingId) : undefined
  if (rec) meetingId = meetingId ?? rec.meeting_id ?? null

  const transcript = recordingId ? deps.getTranscript(recordingId) : undefined
  const meeting = meetingId ? deps.getMeeting(meetingId) : undefined
  const knowledgeKey = knowledgeCaptureId ?? skid
  const detected = knowledgeKey ? deps.getActionablesForKnowledge(knowledgeKey) : []

  const title = (kc?.title || meeting?.subject || rec?.filename || 'handover').toString()
  const attendees = (meeting?.attendees || '')
    .split(/[;,\n]/)
    .map((s) => s.trim())
    .filter(Boolean)
  const recordingIds = recordingId ? [recordingId] : []

  const summaryText = (transcript?.summary || kc?.summary || 'No summary available.').trim() || 'No summary available.'
  const decisionsRaw = (transcript?.key_points || '').trim()
  const decisionsText = decisionsRaw
    ? `# Key Points / Decisions\n\n${decisionsRaw}`
    : '# Key Points / Decisions\n\nNone recorded.'

  return {
    actionableId,
    knowledgeCaptureId,
    meetingId,
    recordingIds,
    title,
    transcriptText: (transcript?.full_text || 'No transcript available.').trim() || 'No transcript available.',
    summaryText: `# Summary\n\n${summaryText}`,
    actionItemsText: formatActionItems(transcript?.action_items, detected),
    decisionsText,
    meetingJson: {
      subject: meeting?.subject ?? null,
      date: meeting?.start_time ?? rec?.date_recorded ?? null,
      attendees,
      meetingId,
      recordingIds,
      knowledgeCaptureId,
    },
  }
}

const README_BODY = `# HiDock Next — Handover Bundle

This folder was generated by **HiDock Next** to hand a meeting's follow-up work
to an AI coding agent (Claude Code / Codex / Gemini CLI).

**Start with \`HANDOVER.md\`** — it is a self-contained prompt describing the work
to do. The \`context/\` folder holds the supporting material the prompt refers to:

- \`context/transcript.md\` — the full meeting transcript
- \`context/summary.md\` — the analysis summary
- \`context/action-items.md\` — extracted action items and detected actionables
- \`context/decisions.md\` — key points / decisions
- \`context/meeting.json\` — meeting metadata (subject, date, attendees, ids)

\`manifest.json\` records which recording/meeting this came from, when it was
generated, and which AI brain was selected. If the agent was run in-app, its
progress and result are appended to \`RUN.log\`.
`

/**
 * Assemble the handover bundle on disk. Pure filesystem + DB reads — no LLM calls,
 * no network. Returns the bundle path, the HANDOVER.md path, and the manifest.
 */
export function assembleHandoverBundle(params: AssembleBundleParams): AssembleBundleResult {
  const now = (params.now ?? (() => new Date()))()
  const deps: HandoverDataDeps = { ...defaultDataDeps, ...(params.data ?? {}) }
  const pathExists = params.pathExists ?? existsSync

  const resolved = resolveSource(params.source, deps)
  const slug = `${timestampSlug(now)}-${slugify(resolved.title)}`
  const parentDir = join(params.targetDir, 'handover')
  const bundleDir = resolveUniqueBundleDir(parentDir, slug, pathExists)
  const contextDir = join(bundleDir, 'context')

  mkdirSync(contextDir, { recursive: true })

  const files: Array<{ rel: string; content: string }> = [
    { rel: 'HANDOVER.md', content: params.handoverContent },
    { rel: 'README.md', content: README_BODY },
    { rel: 'context/transcript.md', content: `# Transcript\n\n${resolved.transcriptText}\n` },
    { rel: 'context/summary.md', content: `${resolved.summaryText}\n` },
    { rel: 'context/action-items.md', content: `${resolved.actionItemsText}\n` },
    { rel: 'context/decisions.md', content: `${resolved.decisionsText}\n` },
    { rel: 'context/meeting.json', content: JSON.stringify(resolved.meetingJson, null, 2) },
  ]

  const manifest: HandoverManifest = {
    slug,
    title: resolved.title,
    generatedAt: now.toISOString(),
    brain: params.brain ?? null,
    source: {
      actionableId: resolved.actionableId,
      knowledgeCaptureId: resolved.knowledgeCaptureId,
      meetingId: resolved.meetingId,
      recordingIds: resolved.recordingIds,
    },
    files: files.map((f) => f.rel).concat('manifest.json'),
  }

  for (const f of files) writeFileSync(join(bundleDir, f.rel), f.content, 'utf-8')
  writeFileSync(join(bundleDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8')

  return { bundleDir, handoverPath: join(bundleDir, 'HANDOVER.md'), manifest }
}

// ── Agentic run ────────────────────────────────────────────────────────────────

export interface RunHandoverAgentParams {
  bundleDir: string
  /** Working directory for the agent (the target repo). */
  targetDir: string
  /** Explicit brain to use; when absent the router resolves the 'handover' task. */
  brainId?: string
  signal?: AbortSignal
  /** Injected for tests. */
  now?: () => Date
  /** Injected for tests. */
  resolveBrain?: (brainId?: string) => Promise<AIBrain | null>
  /** Injected for tests. */
  emit?: (type: string, payload: Record<string, unknown>) => void
}

export interface RunHandoverAgentResult {
  ok: boolean
  brainId: string | null
  brainLabel: string | null
  finalResponse: string | null
  runLogPath: string
  error?: string
}

/**
 * Resolve the agentic brain for a run: an explicit, enabled, configured, agentic
 * brain wins; otherwise the BrainRouter resolves the 'handover' task with the
 * 'agentic' capability (respecting Settings default/routing). Returns null when no
 * agentic brain is usable — the caller surfaces that as a failure, never silence.
 */
async function defaultResolveBrain(brainId?: string): Promise<AIBrain | null> {
  if (brainId) {
    const brain = getBrainRegistry().get(brainId as AIBrain['id'])
    if (brain && brain.capabilities().has('agentic')) {
      try {
        if ((await brain.authStatus()).configured) return brain
      } catch {
        /* fall through to the router */
      }
    }
  }
  return getBrainRouter().resolve('handover', 'agentic')
}

function buildRunPrompt(bundleDir: string, targetDir: string): string {
  const handoverPath = join(bundleDir, 'HANDOVER.md')
  const contextDir = join(bundleDir, 'context')
  return [
    'You are receiving a handover of follow-up work from HiDock Next.',
    '',
    `A handover bundle has been written to:`,
    `  ${bundleDir}`,
    '',
    `1. First read the handover prompt: "${handoverPath}".`,
    `2. Then read the supporting material in "${contextDir}" (transcript, summary, action items, decisions, meeting metadata).`,
    '',
    `Your working directory for this task is:`,
    `  ${targetDir}`,
    '',
    'Carry out the follow-up work described in the handover prompt, operating inside that working directory.',
  ].join('\n')
}

/**
 * Run the handover through an agentic brain, in-app. Writes a RUN.log alongside the
 * bundle and emits event-bus events so the Activity Log can surface progress. Uses
 * the brain's `generate()` as the invocation surface and honours its never-throw /
 * null contract: a null result is a surfaced failure written to RUN.log, not silence.
 */
export async function runHandoverAgent(params: RunHandoverAgentParams): Promise<RunHandoverAgentResult> {
  const now = params.now ?? (() => new Date())
  const resolveBrain = params.resolveBrain ?? defaultResolveBrain
  const emit =
    params.emit ??
    ((type: string, payload: Record<string, unknown>) =>
      getEventBus().emitDomainEvent({ type, timestamp: now().toISOString(), payload }))
  const runLogPath = join(params.bundleDir, 'RUN.log')

  const appendLog = (line: string) => {
    try {
      appendFileSync(runLogPath, line.endsWith('\n') ? line : `${line}\n`, 'utf-8')
    } catch (e) {
      console.error('[handover] failed to append RUN.log:', e)
    }
  }

  const brain = await resolveBrain(params.brainId)
  if (!brain) {
    const error =
      'No agentic AI brain is available. Enable and sign in to Claude Code, Codex, or Gemini CLI in Settings → AI Brains.'
    appendLog(`[${now().toISOString()}] HANDOVER RUN FAILED — ${error}`)
    emit('handover:run-failed', { bundleDir: params.bundleDir, brainId: params.brainId ?? null, error })
    return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath, error }
  }

  const started = now().toISOString()
  appendLog(`[${started}] HANDOVER RUN STARTED`)
  appendLog(`  brain: ${brain.label} (${brain.id})`)
  appendLog(`  target: ${params.targetDir}`)
  appendLog(`  bundle: ${params.bundleDir}`)
  appendLog('')
  emit('handover:run-started', { bundleDir: params.bundleDir, brainId: brain.id, targetDir: params.targetDir })

  const prompt = buildRunPrompt(params.bundleDir, params.targetDir)

  let finalResponse: string | null = null
  try {
    // `generate()` NEVER throws by contract — it returns null on failure/cancel.
    finalResponse = await brain.generate([{ role: 'user', content: prompt }], { signal: params.signal })
  } catch (e) {
    // Defensive: even though the contract forbids it, never let a throw escape.
    console.error('[handover] brain.generate threw (contract violation):', e)
    finalResponse = null
  }

  const ended = now().toISOString()
  if (finalResponse && finalResponse.trim()) {
    appendLog(finalResponse.trim())
    appendLog('')
    appendLog(`[${ended}] HANDOVER RUN COMPLETED`)
    emit('handover:run-completed', { bundleDir: params.bundleDir, brainId: brain.id, ok: true })
    return { ok: true, brainId: brain.id, brainLabel: brain.label, finalResponse: finalResponse.trim(), runLogPath }
  }

  const error =
    'The agent returned no output — it may have failed, been cancelled, timed out, or not be authenticated. Check Settings → AI Brains.'
  appendLog(`[${ended}] HANDOVER RUN FAILED — ${error}`)
  emit('handover:run-failed', { bundleDir: params.bundleDir, brainId: brain.id, error })
  return { ok: false, brainId: brain.id, brainLabel: brain.label, finalResponse: null, runLogPath, error }
}
