name: Auto Labeler

on:
  # Disabled until labeler configuration is created
  # issues:
  #   types: [opened, edited]
  workflow_dispatch:

jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add labels to issues
        uses: anolilab/labeler@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
